export default {
  ROLES: {
    BROKER: 'BROKER',
    SUPERBROKER: 'SUPERBROKER',
  },
  PERMISSIONS: {
    WORKER_VIEW_REWARD: 'WORKER_VIEW_REWARD',
    WORKER_CREATE_BROKERS: 'WORKER_CREATE_BROKERS',
    ORDERS_BROKER_VIEW_SELF_ORDERS: 'ORDERS_BROKER_VIEW_SELF_ORDERS',
    ORDERS_BROKER_VIEW_ORGANIZATION_ORDERS: 'ORDERS_BROKER_VIEW_ORGANIZATION_ORDERS',
  }
};
