// auth
export const AUTH_RESET = 'AUTH_RESET';
export const AUTH_SET_FIELD = 'AUTH_SET_FIELD';

// user
export const USER_RESET = 'USER_RESET';
export const USER_SET_FIELD = 'USER_SET_FIELD';

// application
// -- list
export const APPLICATION_LIST_SET = 'APPLICATION_LIST_SET';
export const APPLICATION_LIST_RESET = 'APPLICATION_LIST_RESET';
export const APPLICATION_LIST_SET_FILTER = 'APPLICATION_LIST_SET_FILTER';
export const APPLICATION_LIST_SET_FETCHING_STATUS = 'APPLICATION_LIST_SET_FETCHING_STATUS';

// reward
// -- list
export const REWARD_LIST_SET = 'REWARD_LIST_SET';
export const REWARD_LIST_RESET = 'REWARD_LIST_RESET';
export const REWARD_LIST_SET_FILTER = 'REWARD_LIST_SET_FILTER';
export const REWARD_LIST_SET_FETCHING_STATUS = 'REWARD_LIST_SET_FETCHING_STATUS';

// document
export const DOCUMENT_RESET = 'DOCUMENT_RESET';
export const DOCUMENT_DELETE_FILE = 'DOCUMENT_DELETE_FILE';
export const DOCUMENT_UPDATE_FILES = 'DOCUMENT_UPDATE_FILES';
export const DOCUMENT_UPDATE_FILE_UPLOAD_PROGRESS = 'DOCUMENT_UPDATE_FILE_UPLOAD_PROGRESS';

// uiMessages
export const UI_MESSAGES_RESET = 'UI_MESSAGES_RESET';
export const UI_MESSAGES_REMOVE_ONE = 'UI_MESSAGES_REMOVE_ONE';
export const UI_MESSAGES_ADD_MESSAGE = 'UI_MESSAGES_ADD_MESSAGE';

// workers
export const WORKERS_RESET = 'WORKERS_RESET';
export const WORKERS_SET_DATA = 'WORKERS_SET_DATA';
export const WORKERS_SET_FETCHING_STATUS = 'WORKERS_SET_FETCHING_STATUS';

// main
export const MAIN_RESET = 'MAIN_RESET';
export const MAIN_SET_FIELD = 'MAIN_SET_FIELD';
